version: "3"

services:
  webserver:
    build: 
      context: .
    container_name: testx_2
    environment:
      - PUID=1000
      - PGID=1000
      #- TZ=America/Caracas
    restart: 'always'
    ports:
      - "4:3838"
    volumes: 
      - ./container:/home/app